import type {Metadata} from 'next'
import './globals.css'
import {inter} from "@/app/ui/fonts";
import Header from "@/app/ui/non-auth/Header";
import Footer from "@/app/ui/non-auth/Footer";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={`${inter.className} antialiased`}>
        <main className="flex min-h-screen flex-col items-center p-24">
            <Header/>

            <div className={'my-auto flex flex-row w-full items-center justify-center'}>
                {children}
            </div>

            <Footer />
        </main>
        </body>
        </html>
    )
}
